### ISSUE TITLE
depth from polarisation

### ISSUE THREAD

**Issue by faezeh-mortazavi** [waps101/depth-from-polarisation#1]
Dear prof. William A. P. Smith  @waps101 
Thank you for sharing the codes. I have a question about it: I saw the results of surface normals in your amazing paper. How can we estimate surface normals from these codes?

**Comment by waps101** [comment]
I recommend using the following function from another of my repositories:

https://github.com/waps101/polarisation_optimisation/blob/master/utils/depthnormals_mask.m

This computes a normal map from a height map via finite difference derivatives. Apply this to the height map you get from shape-from-polarisation.
