### ISSUE TITLE
The results of running the Demo are different from the original paper

### ISSUE THREAD

**Issue by Wangyouai** [waps101/depth-from-polarisation#3]
Hi Prof. Smith,
Thank you so much for open-sourcing this excellent work, I recently ran your demo and noticed a gap between the results and the results in your paper：

![PaperImg](https://user-images.githubusercontent.com/66054562/152953749-10972963-3e75-49ec-9c63-9da591a9e481.png)  ![MyResult](https://user-images.githubusercontent.com/66054562/152954071-72acda08-8e9b-4943-9d2d-f91686fe4cf9.png) 

Here is the detailed code I ran
```
load sampleData.mat
[ rho_est,phi_est,Iun_est ] = PolarisationImage( images,angles,mask,'linear' );
n = 1.5;

theta_est= rho_diffuse(rho_est,n);
theta_est_combined=theta_est;
theta_s = rho_spec(rho_est(spec),n);
theta_est_combined(spec)=theta_s;
phi_est_combined = phi_est;
phi_est_combined(spec)=mod(phi_est(spec)+pi/2,pi);

% Estimate light source direction from diffuse pixels (note that you might
s = [2 0 7]';
[ s,T,B ] = findLight( theta_est,phi_est,Iun_est,mask&~spec,3,s );

% Compute boundary prior azimuth angles and weight
[ azi,Bdist ] = boundaryPrior( mask );

% Run linear height from polarisation
[ height ] = HfPol( theta_est_combined,min(1,Iun_est),phi_est_combined,s,mask,false,spec );

% Visualise
figure;
surf(height,'EdgeColor','none','FaceColor',[0 0 1],'FaceLighting','gouraud','AmbientStrength',0,'DiffuseStrength',1); axis equal; light
```
Can you help me, thanks a lot

**Comment by Wangyouai** [comment]
Thanks to the author's help, here you only need to add boundary conditions and change the direction of the rendering light source, you can get the ideal result, the code is as follows：
`[ azi,Bdist ] = boundaryPrior( mask );`
`[ height ] = HfPol( theta_est,min(1,Iun_est),phi_est,s,mask,false,spec,azi,Bdist);`
`light('Position',[1 1 1]`
**result**:
![2022-02-11 22-21-09屏幕截图](https://user-images.githubusercontent.com/66054562/153608276-66664b4f-7cc6-4da8-bfc1-92d748a52ed0.png)

**Comment by im-peanut** [comment]
Thank you so much, bro
